# Generated by Django 4.0.3 on 2022-03-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuralnet',
            name='features_input',
            field=models.FileField(upload_to='files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='neuralnet',
            name='labels_input',
            field=models.FileField(upload_to='files/%Y/%m/%d/'),
        ),
    ]
