# Generated by Django 4.0.3 on 2022-03-22 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytica', '0005_logisticregression'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perceptron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('features_input', models.FileField(upload_to='files/%Y/%m/%d/')),
                ('labels_input', models.FileField(upload_to='files/%Y/%m/%d/')),
                ('plot', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/')),
                ('weights_file', models.FileField(blank=True, upload_to='files/%Y/%m/%d/')),
                ('model_accuracy', models.FloatField(default=0.0)),
                ('slug', models.SlugField(blank=True, max_length=600)),
                ('created', models.DateField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perceptron_models_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
